server:
  port: 2203
## Logging settings
logging:
  path: /var/logs/
  file: TacoCloud.log
  pattern:
    ## default date format: yyyy-MM-dd HH:mm:ss.SSS
    dateformat: dd-MM-yyyy HH:mm:ss.SSS
  level:
    ## Options OFF/INFO/WARN/DEBUG
    root: INFO
    org:
      springframework:
        security: INFO
spring:
  main:
    ## show banner CONSOLE/LOG/OFF
    banner-mode: LOG
  ## Database settings
  datasource:
    initialisation: always
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
    ## initialise db:
    schema:
      - classpath:schema.sql
    data:
      - classpath:ingredients.sql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect